<?php

namespace Sportakal\Digitalplanet\Constants;

class Currencies
{
    public const AED = 'AED'; //Dirhams
    public const AFN = 'AFN'; //Afgan
    public const ALL = 'ALL'; //Lek
    public const AMD = 'AMD'; //Dram
    public const ANG = 'ANG'; //Antiller Guldeni
    public const AOA = 'AOA'; //Kwanza
    public const ARS = 'ARS'; //Arjantin Pesosu
    public const AUD = 'AUD'; //Avustralya Doları
    public const AWG = 'AWG'; //Aruba Florini
    public const AZN = 'AZN'; //Azerbaycan Manatı
    public const BAM = 'BAM'; //Konvertible Mark
    public const BBD = 'BBD'; //Barbados Doları
    public const BDT = 'BDT'; //Taka
    public const BGN = 'BGN'; //Bulgaristan  Levi
    public const BHD = 'BHD'; //Bahreyn Dinarı
    public const BIF = 'BIF'; //Burundi Frankı
    public const BMD = 'BMD'; //Bermuda Doları (Bermuda Dolar olarak da bilinir.)
    public const BND = 'BND'; //Brunei Doları
    public const BOB = 'BOB'; //Bolivya Bolivyanosu
    public const BOV = 'BOV'; //Bolivya Mvdolu (Para kodu)
    public const BRL = 'BRL'; //Brazilya Reali
    public const BSD = 'BSD'; //Bahama Doları
    public const BTN = 'BTN'; //Ngultrum
    public const BWP = 'BWP'; //Botsvana Pulası
    public const BYR = 'BYR'; //Belarus Rublesi
    public const BZD = 'BZD'; //Belize Doları
    public const CAD = 'CAD'; //Kanada Doları
    public const CDF = 'CDF'; //Kongo Frankı
    public const CHE = 'CHE'; //WIR Euro (Tamamlayıcı para birimi)
    public const CHF = 'CHF'; //İsviçre Frankı
    public const CHW = 'CHW'; //WIR Franc (Tamamlayıcı para birimi)
    public const CLF = 'CLF'; //Unidades de formento (Para kodu)
    public const CLP = 'CLP'; //Şili Pesosu
    public const CNY = 'CNY'; //Yuan Renminbisi
    public const COP = 'COP'; //Kolombiya Pesosu
    public const cou = 'cou'; //Unidad de Valor Real
    public const CRC = 'CRC'; //Kosta Rika Colonu
    public const CUP = 'CUP'; //Küba Pesosu
    public const CVE = 'CVE'; //Cape Verde Escudosu
    public const CYP = 'CYP'; //Kıbrıs Lirası
    public const CZK = 'CZK'; //Çek Korunası
    public const DJF = 'DJF'; //Cibuti Frankı
    public const DKK = 'DKK'; //Danimarka Kronu
    public const DOP = 'DOP'; //Dominik Pesosu
    public const DZD = 'DZD'; //Cezayir Dinarı
    public const EEK = 'EEK'; //Estonya Kronu
    public const EGP = 'EGP'; //Mısır Lirası/ Gineih
    public const ERN = 'ERN'; //Nakfa
    public const ETB = 'ETB'; //Etiyopya Birri
    public const EUR = 'EUR'; //Avro
    public const FJD = 'FJD'; //Fiji Doları
    public const FKP = 'FKP'; //Falkland Adaları Lirası
    public const GBP = 'GBP'; //İngiliz Sterlini/İngiliz Lirası
    public const GEL = 'GEL'; //Gürcistan Lirası/ Lari
    public const GHC = 'GHC'; //Cedi
    public const GIP = 'GIP'; //Cebelitarık Lirası
    public const GMD = 'GMD'; //Dalasi
    public const GNF = 'GNF'; //Gine Frangı
    public const GTQ = 'GTQ'; //Guatemala Kuetzalı
    public const GYD = 'GYD'; //Guyana Doları
    public const HKD = 'HKD'; //Hong Kong Doları
    public const HNL = 'HNL'; //Honduras Lempirası
    public const HRK = 'HRK'; //Hırvatistan Kunası
    public const HTG = 'HTG'; //Haiti Gourde
    public const HUF = 'HUF'; //Macar Forinti
    public const IDR = 'IDR'; //Rupiah
    public const ILS = 'ILS'; //İsrail Yeni Şekeli
    public const INR = 'INR'; //Hindistan Rupisi
    public const IQD = 'IQD'; //Irak Dinarı
    public const IRR = 'IRR'; //İran Riyali
    public const ISK = 'ISK'; //İzlanda Kronası
    public const JMD = 'JMD'; //Jamaika Doları
    public const JOD = 'JOD'; //Ürdün Dinarı
    public const JPY = 'JPY'; //Japon Yeni
    public const KES = 'KES'; //Kenya Şilini
    public const KGS = 'KGS'; //Kırgızistan Somu
    public const KHR = 'KHR'; //Riel
    public const KMF = 'KMF'; //Komoro Frankı
    public const KPW = 'KPW'; //Kuzey Kore Wonu
    public const KRW = 'KRW'; //Güney Kore Wonu
    public const KWD = 'KWD'; //Kuveyt Dinarı
    public const KYD = 'KYD'; //Cayman Adaları Doları
    public const KZT = 'KZT'; //Kazak Tengesi
    public const LAK = 'LAK'; //Kip
    public const LBP = 'LBP'; //Lübnan Lirası
    public const LKR = 'LKR'; //Sri Lanka Rupisi
    public const LRD = 'LRD'; //Liberya Doları
    public const LSL = 'LSL'; //Loti
    public const LTL = 'LTL'; //Litvanya Litası
    public const LVL = 'LVL'; //Letonya Latsı
    public const LYD = 'LYD'; //Libya Dinarı
    public const MAD = 'MAD'; //Fas Dirhemı
    public const MDL = 'MDL'; //Moldovya Leusu
    public const MGA = 'MGA'; //Madagaskar Ariarisi
    public const MKD = 'MKD'; // Makedon Dinarı
    public const MMK = 'MMK'; //Kyat
    public const MNT = 'MNT'; //Tugrik
    public const MOP = 'MOP'; //Macau Patakası
    public const MRO = 'MRO'; //Ouguiya
    public const MTL = 'MTL'; //Malta Lirası
    public const MUR = 'MUR'; //Mauritius Rupisi
    public const MVR = 'MVR'; //Maldiv Rupisi Rufiyaa
    public const MWK = 'MWK'; //Kwacha
    public const MXN = 'MXN'; //Meksika Pesosu
    public const MXV = 'MXV'; //Mexican Unidad de lnversion (UDi) (Para kodu)
    public const MYR = 'MYR'; //Malezya Ringgiti
    public const MZN = 'MZN'; //Mozambik Metikali
    public const NAD = 'NAD'; //Namibya Doları
    public const NGN = 'NGN'; //Naira
    public const NIO = 'NIO'; //Kordoba
    public const NOK = 'NOK'; //Norveç Kronu
    public const NPR = 'NPR'; //Nepal Rupisi
    public const NZD = 'NZD'; //Yeni Zelanda Doları
    public const OMR = 'OMR'; //Umman Riyali
    public const PAB = 'PAB'; //Balboa
    public const PEN = 'PEN'; //Nuevo Sol
    public const PGK = 'PGK'; //Kina
    public const PHP = 'PHP'; //Filipinler Pesosu
    public const PKR = 'PKR'; //Pakistan Rupisi
    public const PLN = 'PLN'; //Leh Zlotisi
    public const PYG = 'PYG'; //Guarani
    public const QAR = 'QAR'; //Katar Riyali
    public const ROL = 'ROL'; //Eski Romanya Leyi
    public const RON = 'RON'; //Yeni Ley
    public const RSD = 'RSD'; //Sırbistan Dinarı
    public const RUB = 'RUB'; //Rus Rublesi
    public const RWF = 'RWF'; //Rıanda Frankı
    public const SAR = 'SAR'; //Suudi Riyali
    public const SBD = 'SBD'; //Solomon Adaları Doları
    public const SCR = 'SCR'; //Seyşeller Rupisi
    public const SDD = 'SDD'; //Sudan Dinar'ı
    public const SEK = 'SEK'; //İsveç Kronu
    public const SGD = 'SGD'; //Singapur Doları
    public const SHP = 'SHP'; //Saint Helena Lira
    public const SIT = 'SIT'; //Tolar
    public const SKK = 'SKK'; //Slovak Korunası
    public const SLL = 'SLL'; //Leone
    public const sos = 'sos'; //Somali Şilini
    public const SRD = 'SRD'; //Surinam Doları
    public const STD = 'STD'; //Dobra
    public const SYP = 'SYP'; //Suriye Lirası
    public const SZL = 'SZL'; //Lilangeni
    public const THB = 'THB'; //Baht
    public const TJS = 'TJS'; //Somoni
    public const TMM = 'TMM'; //Turkmenistan Manatı
    public const TND = 'TND'; //Tunus Dinarı
    public const TOP = 'TOP'; //Pa'anga
    public const TRY = 'TRY'; //Türk Lirası
    public const TTD = 'TTD'; //Trinidad ve Tobago Doları
    public const TWD = 'TWD'; //Yeni Tayvan Doları
    public const TZS = 'TZS'; //Tanzanya Şilini
    public const UAH = 'UAH'; //Ukrayna Grivnası
    public const UGX = 'UGX'; //Uganda Şilini
    public const USD = 'USD'; //Amerikan Doları
    public const USN = 'USN'; //
    public const uss = 'uss'; //
    public const UYU = 'UYU'; //Uruguay Pesosu
    public const uzs = 'uzs'; //Özbekistan Somu
    public const VEB = 'VEB'; //Venezuela Bolivarı
    public const VND = 'VND'; //Dong
    public const vuv = 'vuv'; //Vatu
    public const WST = 'WST'; //Samoa  alası
    public const XAF = 'XAF'; //CFA Franc BEAC
    public const XAU = 'XAU'; //Gümüş (1Troy ons) (=31.1034768 gram)
    public const XAU_ = 'XAU'; //Altın (1Troy ons) (=31.1034768 gram)
    public const XBA = 'XBA'; //Avrupa Para Birimi (EURCO) (Bond Piyasası Birimi)
    public const XBB = 'XBB'; //Avrupa Para Birimi (E.M.U.-6) (Bond Piyasası Birimi)
    public const XBC = 'XBC'; //Avrupa Hesap Birimi 9 (E.U.A.-9) (Bond Piyasası Birimi)
    public const XBD = 'XBD'; //Avrupa Hesap Birimi 17 (E.U.A.-17) (Bond Piyasası Birimi)
    public const XCD = 'XCD'; //Doğu Karayip doları
    public const XDR = 'XDR'; //Özel Çekme Hakları
    public const XFO = 'XFO'; //Altın Frank (özel ödeme para birimi)
    public const XFU = 'XFU'; //UIC Frank (özel ödeme para birimi)
    public const XOF = 'XOF'; //CFA Franc BCEAO
    public const XPD = 'XPD'; //Palladium (13 gram Truva)
    public const XPF = 'XPF'; //CFP franc
    public const XPT = 'XPT'; //Platin (13 gram Truva)(= 31.1034768 gram)
    public const XTS = 'XTS'; //test edilen para birimleri için kullanılır
    public const xxx = 'xxx'; //Böyle Bir Para Birimi Yok
    public const YER = 'YER'; //Yemen Riyali
    public const ZAR = 'ZAR'; //Güney Afrika Randı
    public const ZMK = 'ZMK'; //Kwacha
    public const ZWD = 'ZWD'; //Zimbabve Doları
}
